keys:
  - &users
    - &da age16fpnlw0yzfgsk246qu3v3jwle44uvwpj6yl26cl4gf6pmwy9ldaqynrj0m
  - &hosts
    - &t470 age1j0mcw4nnvskkn6g4ve05zf2jg795vgdnwj0g3eefk68w7uvrfepscmme2f
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *da
        - *t470
