#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 5

bspc config top_padding 35
bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5

bspc config border_width         2
bspc config focused_border_color "#cba6f7"
bspc config active_border_color "#a6adc8"
bspc config normal_border_color "#313244"

bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config pointer_motion_interval 7ms
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# starts start apps
sa
